CREATE TABLE users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dtype        VARCHAR(31),
    email        VARCHAR(255),
    password     VARCHAR(255),
    display_name VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE courses
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_courses PRIMARY KEY (id)
);

CREATE TABLE class_groups
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255),
    course_id BIGINT,
    CONSTRAINT pk_class_groups PRIMARY KEY (id)
);

ALTER TABLE class_groups
    ADD CONSTRAINT FK_CLASS_GROUPS_ON_COURSE FOREIGN KEY (course_id) REFERENCES courses (id);

CREATE TABLE class_groups_coaches
(
    class_group_id BIGINT NOT NULL,
    coach_id       BIGINT NOT NULL
);

ALTER TABLE class_groups_coaches
    ADD CONSTRAINT fk_clagrocoa_on_class_group FOREIGN KEY (class_group_id) REFERENCES class_groups (id);

ALTER TABLE class_groups_coaches
    ADD CONSTRAINT fk_clagrocoa_on_coach FOREIGN KEY (coach_id) REFERENCES users (id);

CREATE TABLE class_groups_students
(
    class_group_id BIGINT NOT NULL,
    student_id     BIGINT NOT NULL
);

ALTER TABLE class_groups_students
    ADD CONSTRAINT fk_clagrostu_on_class_group FOREIGN KEY (class_group_id) REFERENCES class_groups (id);

ALTER TABLE class_groups_students
    ADD CONSTRAINT fk_clagrostu_on_student FOREIGN KEY (student_id) REFERENCES users (id);

CREATE TABLE modules
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dtype            VARCHAR(31),
    name             VARCHAR(255),
    parent_module_id BIGINT,
    CONSTRAINT pk_modules PRIMARY KEY (id)
);

ALTER TABLE modules
    ADD CONSTRAINT FK_MODULES_ON_PARENT_MODULE FOREIGN KEY (parent_module_id) REFERENCES modules (id);

CREATE TABLE codelabs
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255),
    module_id BIGINT,
    CONSTRAINT pk_codelabs PRIMARY KEY (id)
);

ALTER TABLE codelabs
    ADD CONSTRAINT FK_CODELABS_ON_MODULE FOREIGN KEY (module_id) REFERENCES modules (id);

CREATE TABLE progresses
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_progresses PRIMARY KEY (id)
);

CREATE TABLE codelab_progresses
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codelab_id  BIGINT,
    progress_id BIGINT,
    student_id  BIGINT,
    CONSTRAINT pk_codelab_progresses PRIMARY KEY (id)
);

ALTER TABLE codelab_progresses
    ADD CONSTRAINT FK_CODELAB_PROGRESSES_ON_CODELAB FOREIGN KEY (codelab_id) REFERENCES codelabs (id);

ALTER TABLE codelab_progresses
    ADD CONSTRAINT FK_CODELAB_PROGRESSES_ON_PROGRESS FOREIGN KEY (progress_id) REFERENCES progresses (id);

ALTER TABLE codelab_progresses
    ADD CONSTRAINT FK_CODELAB_PROGRESSES_ON_STUDENT FOREIGN KEY (student_id) REFERENCES users (id);

CREATE TABLE comments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text       TEXT,
    user_id    BIGINT,
    codelab_id BIGINT,
    CONSTRAINT pk_comments PRIMARY KEY (id)
);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_CODELAB FOREIGN KEY (codelab_id) REFERENCES codelabs (id);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);
